    -- MySQL Script generated by MySQL Workbench
    -- Sat Jun 13 13:53:40 2026
    -- Model: New Model    Version: 1.0
    -- MySQL Workbench Forward Engineering

    SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
    SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
    SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

    -- -----------------------------------------------------
    -- Schema db
    -- -----------------------------------------------------

    -- -----------------------------------------------------
    -- Schema db
    -- -----------------------------------------------------
    CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
    USE `db` ;

    -- -----------------------------------------------------
    -- Table `db`.`LOCATIONS`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `db`.`LOCATIONS` (
    `id` INT NOT NULL,
    `name` VARCHAR(45) NULL,
    `city` VARCHAR(45) NULL,
    `state` VARCHAR(45) NULL,
    `photo` VARCHAR(200) NULL,
    `availableUnits` INT NULL,
    `wifi` TINYINT NULL,
    `laundry` TINYINT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


    SET SQL_MODE=@OLD_SQL_MODE;
    SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
    SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
